### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [52]:
import numpy as np
from math import sqrt

In [32]:
# Creadas dos matrices de forma aleatoria
x = random.randint(10, size=(5))
y = random.randint(100, size=(3, 5))

# la función comprueba la dimensión y retorna un resultado.
def data (array):
    if array.ndim > 1:
        return ("El array no puede tener más de una dimensión.")
    else:
        return (array)

# se invoca la función con parametros introducidos.
print (data(x))
print (data(y))

[2 6 7 4 4]
El array no puede tener más de una dimensión.


### Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [1]:
# se importa la función random. Se pide un número mediante input, que será la cantidad de filas y columnas.
y = input ("Introduce un número: ")
y = int(y)

def square (y):
    x = random.randint(100, size=(y, y))
    return(x)

print(square(y))

KeyboardInterrupt: Interrupted by user

### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.


In [18]:
# Se crea un array de una dimension
arr = np.array ( [1,2,3,4,5,6,7,8])

# se hace un reshape del array a uno de dos dimensiones.
arr2 = arr.reshape (2,4)

print (arr2)

def total (array):
    for x in array:
        x = np.sum(array, axis=0)
        y = np.sum(array, axis=1)
        return ("Total por columna "+str(x)+"\nTotal por fila "+str(y))
    
print (total(arr2))

[[1 2 3 4]
 [5 6 7 8]]
Total por columna [ 6  8 10 12]
Total por fila [10 26]


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [55]:
x = np.array ([3,6,9])
y = np.array ([70,75,80])

# la función requiere recibir los dos ejes en arrays distintos. Después, calcula el valor del dividendo y divisor
# por separado y finalmente da el resultado.
def pearson (x_axis, y_axis):
    x_mean = np.sum(x_axis) / len(x_axis)
    y_mean = np.sum(y_axis) / len(y_axis)

    distance_x = x - x_mean
    distance_y = y - y_mean
    distance = distance_x * distance_y
    dividend = np.sum(distance)

    square_x = (x - x_mean)**2
    square_y = (y - y_mean)**2
    square_x_sum = np.sum(square_x)
    square_y_sum = np.sum(square_y)
    divisor = sqrt(square_x_sum*square_y_sum)
    result = divisor/dividend
    return (result)
    
print(pearson(x, y))

1.0
